mattermost:
  client:
    apiurl: ${MATTERMOST_HOST:YOUR_MATTERMOST_HOST}
    hook: ${MATTERMOST_HOOK:YOUR_MATTERMOST_HOOK}

giphy:
  client:
    apiurl: "https://api.giphy.com/"
    apikey: ${GIPHY_API_KEY:YOUR_GIPHY_APIKEY}

urbandictionary:
  client:
    apiurl: "https://api.urbandictionary.com"
