mattermost:
  client:
    apiurl: "MATTERMOST_HOST"
    hook: "MATTERMOST_HOOK"

giphy:
  client:
    apiurl: "https://api.giphy.com/"
    apikey: "GIPHY_API_KEY"

openweather:
  client:
    apiurl: "https://api.openweathermap.org/"
    apikey: "OPENWEATHER_API_KEY"